name: Deploy to k8s

on:
  push:
    branches:
      - main

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/woog-life/booking-scraper:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/woog-life/booking-scraper:${GITHUB_SHA}

  deploy_woog_family:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@v1
      - name: Create deploy dir
        run: mkdir deploy
      - name: Create woog family config
        env:
          LAKE_NAME: woog-family
        run: envsubst < .kubernetes/cronjob.yaml > deploy/cronjob_woog_family.yaml
      - name: Create woog island config
        env:
          LAKE_NAME: woog-island
        run: envsubst < .kubernetes/cronjob.yaml > deploy/cronjob_woog_island.yaml
      - name: Create muehlchen config
        env:
          LAKE_NAME: muehlchen
        run: envsubst < .kubernetes/cronjob.yaml > deploy/cronjob_muehlchen.yaml
      - uses: danielr1996/kubectl-action@1.0.0
        name: apply config
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -f deploy
